version: '3.8'

services:
  api:
    container_name: api
    restart: unless-stopped
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
  client:
    container_name: client
    restart: unless-stopped
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000


